---
- name: Cau hinh tren Switch
  hosts: SW
  gather_facts: no
  tasks:
   - name: tao vlan
     ios_vlan:
      aggregate:
       - { vlan_id : 10 }
       - { vlan_id : 20 }
       - { vlan_id : 30 }
   - name: gan cong vao vlan
     ios_l2_interface:
     name: "{{ item.int }}"
     mode: access
     access_vlan: "{{ item.vlan }}"
     with_items: # thay the cac cong
      - { vlan: "10", int: "Ethernet0/1"}
      - { vlan: "20", int: "Ethernet0/2"}
      - { vlan: "30", int: "Ethernet0/3"}
   - name: chuyen cong E0/0 sang mode trunk
     ios_config:
      parents: #thay the bang cong Switch ket noi den Router
       - int Ethernet0/0
      lines:
       - sw trunk encapsulation dot1Q
       - sw mode trunk

