---
- name: Cau hinh tren Switch
  hosts: SW
  gather_facts: no
  tasks:
   - name: tao vlan
     ios_vlan:
      aggregate:
       - { vlan_id : 10 }
       - { vlan_id : 20 }
       - { vlan_id : 30 }
   - name: Ensure GigabitEthernet0/5 is a trunk port and ensure 2-50 are being tagged (doesn't mean others aren't also being tagged)
     ios_l2_interface:
       name: Ethernet0/1
       mode: trunk
    
